version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    reviewers:
      - 'Sumolari'
    assignees:
      - 'Sumolari'
    versioning-strategy: increase
