name: 'test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [ubuntu-latest]
    steps:
      - name: Install git
        run: |
          sudo apt-get update 
          sudo apt-get install -y git
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint:source
      - name: Tests
        run: yarn test
      - name: Upload coverage
        uses: caffco/code-climate-github-action@v0.0.1-alpha.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          repository_root_path: ${{github.workspace}}
          collect_coverage: 'true'
          coverage_file_patterns: |
            coverage/lcov.info:lcov
      - name: Build
        run: yarn build
